### ISSUE TITLE
Board name for Circuit Dojo in mRF91 Quickstart

### ISSUE THREAD

**Issue by vitprajzler** [golioth/docs#131]
The current Zephyr release has only two boards defined for the Circuit Dojo Feathers, 
`circuitdojo_feather_nrf9160` and `circuitdojo_feather_nrf9160ns`.

The nRF91 quickstart guide lists `circuitdojo_feather_nrf9160_ns` as target, which does not exist. It should say one of the board names above.

**Comment by szczys** [comment]
nRF91 Quick Start overview page page directs user to hardware section. This should probably be updated to the `Board Catalog` section:

> See the [Hardware](https://docs.golioth.io/hardware) section for more devices that use the nRF91

https://docs.golioth.io/hardware/nrf91/quickstart

**Comment by mniestroj** [comment]
`circuitdojo_feather_nrf9160_ns` is the correct name, so docs are right in that case. However wrong NCS revision was specified, which is why `circuitdojo_feather_nrf9160_ns` was non-existing and `circuitdojo_feather_nrf9160ns` was. So after merging #139 and following quickstart for nRF91 Feather, everything should work.

**Comment by vitprajzler** [comment]
Changes in #139 fix this. Closing.

**Comment by mniestroj** [comment]
@vitprajzler FYI when #139 would be merged, then this issue would be closed automatically due to usage of "Fixes: <issue_number>" in PR description (see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). So there is no need to do it manually.
