### ISSUE TITLE
Feather getting started issues

### ISSUE THREAD

**Issue by vancefarren** [golioth/docs#140]
Additional documentation/tools/instruction will be required to get users going with the nrf91 feather.

Started a Doc here at @vitprajzler 's request

https://golioth.atlassian.net/wiki/spaces/DSDK/pages/edit-v2/195166302?draftShareId=3e13112e-8c18-44e7-8a71-ca28740d3d37

**Comment by szczys** [comment]
As discussed at today's standup, we should have board/platform specific toolchain and flashing information as part of the Board Catalog so that it's easier to keep the Quickstart quick as we scale up the number of supported boards.

I'll look into how these sections can be added to the JSON data the catalog pulls from and work on adding information about programming the feather, then link back to it from the quickstart.

**Comment by vitprajzler** [comment]
The scripts to handle the catalog along with a readme is here https://github.com/golioth/docs/tree/main/scripts/device-catalog
Me or @chireia can provide additional information in terms of how it works.

The JSON file is https://github.com/golioth/docs/blob/main/scripts/device-catalog/support.json.

We can e.g. add new keys to that per-board structure for "toolchain" and "flashing"

**Comment by szczys** [comment]
I think we addressed this issue with #158. Please re-open it if you feel more documentation needs to be added:
https://docs.golioth.io/hardware/nrf91/quickstart/flash-firmware/flash-firmware/
