### ISSUE TITLE
Firmware - DFU - Overview

### ISSUE THREAD

**Issue by vancefarren** [golioth/docs#97]

**Comment by 0Grit** [comment]
@vancefarren I would like to make a system diagram the centerpiece of each of the Overview docs. Similar to the Auth section.

https://docs.golioth.io/firmware/device-sdk/authentication/overview-auth

The diagram sources are here https://github.com/golioth/docs/blob/main/docs/firmware/firmware-client-auth.drawio.svg
The bigger picture diagram sources are in google drive.

**Comment by vancefarren** [comment]
@alvarowolfx, in the ota section of the docs advanced capabilities are described in the opening paragraph of the overview.  Are these capabilities documented anywhere? https://docs.golioth.io/cloud/services/ota

@0Grit @ChrisGammell @vitprajzler 

I'll be adding more here after my 2pm meeting

- DFU
  - Why is it needed
  - When is it not needed
  - Benefits
    - Security updates
    - Functionality updates
  - Drawbacks
    - Consumption of flash space by extra image may impact application size
    - Power consumption
    - Security threat of exposed attack vector available through the update mechanism if keys are exposed.
  - Limitations
    - Not all devices have sufficient flash size to support DFU
    - Devices that are not battery powered may not be able to support the power requirements of a DFU transaction
    - Data servicing costs
- MCUBoot
  - build process
  - two image handling description
  - memory considerations
  - security
    - image signing
    - image corruption
- Security
  -

**Comment by vitprajzler** [comment]
Many of the points listed under the "DFU" bullet point should not be part of the firmware docs (for future, it's easier and less ambiguous to reference numbered lists than bullet points). Those points should go under the service description, based on internal docs by the backend team. Some of the other points outlining the rationale are not important right now.

The important information the users need to have is what they can do with the SDK and how to do it. Therefore, the firmware docs in the first iteration should only outline how to use the service from the SDK. 

Once that's done, we can add things like considerations for its usage (such as the things you list under MCUBoot), and further details around "what can be done" with the SDK.

In a user story:
As an embedded engineer I want a guide and sample code for the DFU part of the SDK, so that I can easily start developing my DFU-enabled application (from scratch) or integrate DFU into an existing application.

This first doc doesn't have to be perfect and include everything about DFU. Write a smaller chunk that's limited in scope and demo it, and then move on to another smaller chunk.

**Comment by vitprajzler** [comment]
@szczys, I think this DFU overview topic would use your attention / lead. See my comments above in terms of what I thought this could be.

**Comment by szczys** [comment]
Since this issue was first opened, DFU documentation has been updated for both SDKs:

* [Golioth Zephyr SDK OTA](https://docs.golioth.io/firmware/zephyr-device-sdk/firmware-upgrade/build-sample-application)
* [Golioth Firmware SDK OTA](https://docs.golioth.io/firmware/golioth-firmware-sdk/firmware-upgrade/firmware-upgrade)
